name: Go CI/CD

on:
  push:
    branches: [main]
    paths:
      - 'cmd/**'
      - 'go.mod'
      - 'go.sum'
  release:
    types: [created]

jobs:
  audit:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || github.event_name == 'release'
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.21

    - name: Verify dependencies
      run: go mod verify

    - name: Run go vet
      run: go vet ./...

    - name: Run staticcheck
      run: go run honnef.co/go/tools/cmd/staticcheck@latest -checks=all ./...

    - name: Run golint
      run: go run golang.org/x/lint/golint@latest ./...

    - name: Run tests
      run: go test -race -vet=off ./...

  build:
    needs: audit
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - platform: linux
            arch: amd64
          - platform: darwin
            arch: amd64
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Extract binary name
      run: echo "BINARY_NAME=$(basename $(pwd))" >> $GITHUB_ENV

    - name: Build for ${{ matrix.platform }} ${{ matrix.arch }}
      run: GOOS=${{ matrix.platform }} GOARCH=${{ matrix.arch }} go build -v -trimpaths -a -installsuffix cgo -o bin/${{ env.BINARY_NAME }}-${{ matrix.platform }}-${{ matrix.arch }} ./cmd/${{ env.BINARY_NAME }}

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: binaries
        path: bin/

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./bin/${{ env.BINARY_NAME }}-${{ matrix.platform }}-${{ matrix.arch }}
        asset_name: ${{ env.BINARY_NAME }}-${{ matrix.platform }}-${{ matrix.arch }}
        asset_content_type: application/octet-stream
